/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenSol from "./ERC20Token.sol";
export type { erc20TokenSol };
import type * as sushiRouterSol from "./SushiRouter.sol";
export type { sushiRouterSol };
